repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 77c7147e528b9a7c20f3546a6de3ac0cf6f15859
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 64e5d0b147a43fdbf5ea385a044a62c2fff6efe9
    hooks:
      - id: pretty-format-java
        args: [--autofix]
